# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

networks:
  ssl-reverse-proxy:
    external: yes

services:
  validator-xspf-org:
    build: ./
    ports:
      - 127.0.0.1:52080:80
    networks:
      - default
      - ssl-reverse-proxy
    volumes:
      - .:/var/www/html/
    restart: unless-stopped
