# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

services:
  validator-xpsf-org:
    build: ./
    ports:
      - 127.0.0.1:52080:80
    volumes:
      - .:/var/www/html/
